# Generated by Django 4.2.5 on 2023-10-24 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("White", "White"),
                            ("Silver", "Silver"),
                            ("Yellow", "Yellow"),
                            ("Blue", "Blue"),
                            ("Red", "Red"),
                            ("Green", "Green"),
                            ("Black", "Black"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="advanced_htmx.category"),
                ),
            ],
        ),
    ]
